CREATE OR REPLACE FUNCTION cleanup_fdw()
RETURNS VOID
AS $FUNC$
BEGIN

  DROP SCHEMA model_schema;
  DROP USER MAPPING FOR CURRENT_USER SERVER model_db;
  DROP SERVER model_db;

END $FUNC$ LANGUAGE PLPGSQL;

